# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6d95524971e07209062edfd2821521d4e7d9fda502b3650dfb4ee65a970fd2ce1488a64f0b2ac39360a028d0b36fd1646314a5fcf88ff8ef69289664a8fdee2

test:
  secret_key_base: a7cb2952e88c9f2653efdf855737e57d69e6a2c793ea14c08979f0284b48359adaedebe10fbe21ea17fbbaa4bcd2c899b0d76c69f08fe235d938e3fd2ae8221e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
